version: "3.9"
services:
  front:
    depends_on:
      - "mssql"
      - "rabbit"
    build:
      context: .
      dockerfile: ./Front/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password='xapopass'
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
       - ./cert/:/https/
    ports:
      - "5000:5000"
      - "5001:5001"
  core:
    depends_on:
      - "rabbit"
    build:
      context: .
      dockerfile: ./Core/Dockerfile
  store:
    depends_on:
      - "mssql"
      - "rabbit"
    build:
      context: .
      dockerfile: ./Store/Dockerfile
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "55673:55673"
  mssql:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=passWORD123#@!
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
  
